# **Importing Libraries**

- File reading - Pandas
- Data Manipulation - Numpy

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_squared_error, r2_score

print("Libraries Imported Sucessfully.")

Libraries Imported Sucessfully

# **Reading Files**

In [ ]:
data = pd.read_csv("datasets/loan_data.csv")
print("Data read successfully.")

:

# **Understanding Data**

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

# **Anomaly Detection**
No anomalies found.

In [8]:
# showing first 5 values by default
data.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

# **Separating Numerical & Categorical columns**

In [14]:
num_col = data.select_dtypes(include=['int64','float64']).columns
cat_col = data.select_dtypes(include=['object']).columns

print("Numerical -", list(num_col))
print("Categorical -", list(cat_col))

Numerical - ['person_age', 'person_income', 'person_emp_exp', 'loan_amnt', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length', 'credit_score', 'loan_status']
Categorical - ['person_gender', 'person_education', 'person_home_ownership', 'loan_intent', 'previous_loan_defaults_on_file']

# **Encoding Categorical Columns**

In [15]:
data_encoded = data.copy()
for col in cat_col:
    data_encoded[col] = data_encoded[col].astype('category').cat.codes

In [16]:
data_encoded.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,0,4,71948.0,0,3,35000.0,4,16.02,0.49,3.0,561,0,1
1,21.0,0,3,12282.0,0,2,1000.0,1,11.14,0.08,2.0,504,1,0
2,25.0,0,3,12438.0,3,0,5500.0,3,12.87,0.44,3.0,635,0,1
3,23.0,0,1,79753.0,0,3,35000.0,3,15.23,0.44,2.0,675,0,1
4,24.0,1,4,66135.0,1,3,35000.0,3,14.27,0.53,4.0,586,0,1

# **Splitting data into feature and label**

In [17]:
# subtle error handling
# outputs
target_class = 'loan_status' if ' loan_status' in data_encoded.columns else data_encoded.columns[-1]
target_regr = 'ApplicationIncome' if 'ApplicationIncome' in data_encoded.columns else num_col[-1]

# inputs
x_class = data_encoded.drop(columns=[target_class]) # input for classification
y_class = data_encoded[target_class] # output for classification

x_regr = data_encoded.drop(columns=[target_regr]) # input for regressor
y_regr = data_encoded[target_regr] # output for regressor

# **Data Validation**

In [20]:
# for classification
xc_train, xc_test, yc_train, yc_test = train_test_split(x_class, y_class, test_size=0.2, random_state=42)

# for regressor
xr_train, xr_test, yr_train, yr_test = train_test_split(x_regr, y_regr, test_size=0.2, random_state=42)

# **Decision Tree**

In [23]:
# 1. Classification

dt_clf = DecisionTreeClassifier(random_state=42)

dt_clf.fit(xc_train, yc_train)

yc_pred_dt = dt_clf.predict(xc_test)

In [24]:
# 2. Regression

dt_clf = DecisionTreeRegressor(random_state=42)

dt_clf.fit(xr_train, yr_train)

yr_pred_dt = dt_clf.predict(xr_test)

# **Random Forest**

1. Classification

In [30]:
rf_clf = RandomForestClassifier(random_state=42)

rf_clf.fit(xc_train, yc_train)

yc_pred_rf = rf_clf.predict(xc_test)

2. Regression

In [31]:
rf_reg = RandomForestRegressor(random_state=42)

rf_reg.fit(xr_train, yr_train)

yr_pred_rf = rf_clf.predict(xr_test)

# **Evaluation**

In [42]:
print("==================Classification Results=================")
print("\n DT Accuracy \n", accuracy_score(yc_test,yc_pred_dt))
print("\n RF Accuracy \n", accuracy_score(yr_test,yr_pred_rf))

print("\n Decision Tree Classification Report\n", classification_report(yc_test, yc_pred_dt))
print("\n Random Forest Classification Report\n", classification_report(yc_test, yc_pred_rf))

==================Classification Results=================

 DT Accuracy
 0.8974444444444445

 RF Accuracy
 0.9286666666666666

 Decision Tree Classification Report
               precision    recall  f1-score   support

           0       0.94      0.93      0.93      6990
           1       0.77      0.77      0.77      2010

    accuracy                           0.90      9000
   macro avg       0.85      0.85      0.85      9000
weighted avg       0.90      0.90      0.90      9000


 Random Forest Classification Report
               precision    recall  f1-score   support

           0       0.94      0.97      0.95      6990
           1       0.89      0.78      0.83      2010

    accuracy                           0.93      9000
   macro avg       0.91      0.87      0.89      9000
weighted avg       0.93      0.93      0.93      9000